name: Terraform Deploy

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1   # 👈 set your AWS region here
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=manifests init -input=false

      - name: Terraform Plan
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            terraform -chdir=manifests plan -lock-timeout=5m -var-file="dev/terraform-dev.tfvars"
          elif [[ "${GITHUB_REF_NAME}" == "qa" ]]; then
            terraform -chdir=manifests plan -lock-timeout=5m -var-file="qa/terraform-qa.tfvars"
          else
            terraform -chdir=manifests plan -lock-timeout=5m -var-file="prod/terraform-prod.tfvars"
          fi

      - name: Terraform Apply (only dev)
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: terraform -chdir=manifests apply -auto-approve -lock-timeout=5m -var-file="dev/terraform-dev.tfvars"
