name: Terraform Deploy

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=manifests init

      - name: Terraform Plan
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            terraform -chdir=manifests plan -var-file="dev/terraform-dev.tfvars"
          elif [[ "${GITHUB_REF_NAME}" == "qa" ]]; then
            terraform -chdir=manifests plan -var-file="qa/terraform-qa.tfvars"
          else
            terraform -chdir=manifests plan -var-file="prod/terraform-prod.tfvars"
          fi

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=manifests apply -auto-approve -var-file="prod/terraform-prod.tfvars"
