name: "Terraform action"

on:
  push:
    branches: [dev]

permissions:
  contents: read            # needed for actions/checkout
  id-token: write           # needed for AWS OIDC

env:
  REGION:      ${{ vars.REGION }}
  ROLE_ARN:    ${{ vars.AWS_ROLE_ARN }}
  BUCKET_NAME: ${{ vars.BUCKET_NAME }}

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assume AWS role (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region:     ${{ env.REGION }}

      - name: Create bucket (exercise - minimal)
        run: |
          set -euo pipefail
          echo "Target bucket: $BUCKET_NAME (region: $REGION)"
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket already exists; nothing to do."
          else
            if [ "$REGION" = "us-east-1" ]; then
              aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$REGION"
            else
              aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$REGION" \
                --create-bucket-configuration LocationConstraint="$REGION"
            fi
            echo "Bucket created."
          fi
